// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjqYWHUWXyVMaYMj_dR3wMEiwunPXQhlc',
    appId: '1:753410203184:web:292ca61766321d0a0397f5',
    messagingSenderId: '753410203184',
    projectId: 'cloudnote-9c1a3',
    authDomain: 'cloudnote-9c1a3.firebaseapp.com',
    storageBucket: 'cloudnote-9c1a3.appspot.com',
    measurementId: 'G-XWJSW42MCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxrpdA8Red1j0d6ZtbiMiS2X9E6eFb5ig',
    appId: '1:753410203184:android:d56b195882a08bce0397f5',
    messagingSenderId: '753410203184',
    projectId: 'cloudnote-9c1a3',
    storageBucket: 'cloudnote-9c1a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFAnJJyrH8X5QC5DAu6Rc2iBiPulNibNY',
    appId: '1:753410203184:ios:b7762d23635a6baa0397f5',
    messagingSenderId: '753410203184',
    projectId: 'cloudnote-9c1a3',
    storageBucket: 'cloudnote-9c1a3.appspot.com',
    iosBundleId: 'com.example.quicknote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFAnJJyrH8X5QC5DAu6Rc2iBiPulNibNY',
    appId: '1:753410203184:ios:f32ed03768149d270397f5',
    messagingSenderId: '753410203184',
    projectId: 'cloudnote-9c1a3',
    storageBucket: 'cloudnote-9c1a3.appspot.com',
    iosBundleId: 'com.example.quicknote.RunnerTests',
  );
}
